language: python
services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000"
    env:
      - AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      - AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
      - AWS_DEFAULT_REGION: us-east-2
    command:
      - cd dynamodb_local_latest && java -Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar -sharedDb
python:
  - "3.8.6"
install:
  - pip install pipenv
  - pipenv install --dev
# command to run tests
env:
  - DATABASE_URL: http://localhost:8000/
  - AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
  - AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
  - AWS_DEFAULT_REGION: us-east-2
script:
  - pipenv run python create_dynamodb_table.py
  - make test
