language: python

services:
  - docker

before_install:
- docker pull amazon/dynamodb-local
- docker run -p 8000:8000 amazon/dynamodb-local

python:
  - "3.8.6"
install:
  - pip install pipenv
  - pipenv install --dev
# command to run tests
env:
  - DATABASE_URL=http://localhost:8000 AWS_ACCESS_KEY_ID=DUMMYIDEXAMPLE AWS_SECRET_ACCESS_KEY=DUMMYEXAMPLEKEY AWS_DEFAULT_REGION=us-east-2
links:
  - dynamodb
script:
  - pipenv run python create_dynamodb_table.py
  - make test
